version: "3.8"

services:
  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - labnet

  db-primary:
    image: postgres:14
    container_name: db-primary
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: betting_game
    volumes:
      - ./db-primary/data:/var/lib/postgresql/data
      - ./db-primary/postgresql.conf:/etc/postgresql/postgresql.conf
      - ./db-primary/pg_hba.conf:/var/lib/postgresql/data/pg_hba.conf
    command: ["postgres", "-c", "config_file=/etc/postgresql/postgresql.conf"]
    ports:
      - "5432:5432"
    networks:
      - labnet

  db-replica1:
    image: postgres:14
    container_name: db-replica1
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    volumes:
      - ./db-replica1/data:/var/lib/postgresql/data
      - ./db-replica1/postgresql.conf:/etc/postgresql/postgresql.conf
    depends_on:
      - db-primary
    networks:
      - labnet
    ports:
      - "5433:5432"

  db-replica2:
    image: postgres:14
    container_name: db-replica2
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    volumes:
      - ./db-replica2/data:/var/lib/postgresql/data
      - ./db-replica2/postgresql.conf:/etc/postgresql/postgresql.conf
    depends_on:
      - db-primary
    networks:
      - labnet
    ports:
      - "5434:5432"

  backend1:
    build: ./backend
    container_name: backend1
    environment:
      - PORT=3000
      - REDIS_URL=redis://redis:6379
      - MASTER_DB=postgres://admin:password@db-primary:5432/betting_game
      - READ_REPLICAS=postgres://admin:password@db-replica1:5432,postgres://admin:password@db-replica2:5432
    volumes:
      - ./public:/app/public  
    depends_on:
      - redis
      - db-primary
      - db-replica1
      - db-replica2
    networks:
      - labnet
    ports:
      - "3000:3000"

  backend2:
    build: ./backend
    container_name: backend2
    environment:
      - PORT=3001
      - REDIS_URL=redis://redis:6379
      - MASTER_DB=postgres://admin:password@db-primary:5432/betting_game
      - READ_REPLICAS=postgres://admin:password@db-replica1:5432,postgres://admin:password@db-replica2:5432
    volumes:
      - ./public:/app/public  
    depends_on:
      - redis
      - db-primary
      - db-replica1
      - db-replica2
    networks:
      - labnet
    ports:
      - "3001:3001"

  nginx:   
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./public:/usr/share/nginx/html:ro
    ports:
      - "80:80"
    depends_on:
      - backend1
      - backend2
    networks:
      - labnet

networks:
  labnet:
    driver: bridge
